# Generated by Django 3.1.14 on 2024-10-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20241027_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappear_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата/время исчезновения'),
        ),
    ]
